2021-01-07 17:18:11.651 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-01-07 17:18:11.652 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-01-07 17:18:11.652 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-01-07 17:18:11.652 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-01-07 17:18:11.653 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-01-07 17:18:11.653 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-01-07 17:18:11.654 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-01-07 17:18:11.654 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-01-07 17:18:11.654 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-01-07 17:18:11.655 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-01-07 17:18:11.664 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-01-07 17:18:11.664 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-01-07 17:18:11.665 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-01-07 17:18:11.665 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-01-07 17:18:11.665 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-01-07 17:18:11.666 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-01-07 17:18:11.666 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:209 - Using installed version: setuptools-git==1.2
2021-01-07 17:18:11.673 - INFO - 5956 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-01-07 17:18:13.652 - CRITICAL - 5956 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-01-07 17:18:13.653 - INFO - 5956 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
2021-01-07 17:21:56.813 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package azureml-train-automl missing from dependencies file.
2021-01-07 17:21:56.813 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: azureml-train-automl==1.19.0.*
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package pandas missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: pandas==0.25.1
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package psutil missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: psutil>5.0.0,<6.0.0
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package scikit-learn missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: scikit-learn==0.22.1
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package numpy missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: numpy~=1.18.0
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package py-xgboost missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: py-xgboost<=0.90
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package inference-schema missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package fbprophet missing from dependencies file.
2021-01-07 17:21:56.814 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:205 - Using pinned version: fbprophet==0.5
2021-01-07 17:21:56.815 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:199 - Package setuptools-git missing from dependencies file.
2021-01-07 17:21:56.815 - INFO - 5956 - azureml.train.automl._azureautomlclient.modify_run_configuration:209 - Using installed version: setuptools-git==1.2
2021-01-07 17:21:56.821 - INFO - 5956 - azureml.train.automl._azureautomlclient._validate_input:663 - Start data validation.
2021-01-07 17:21:59.002 - CRITICAL - 5956 - azureml.train.automl._azureautomlclient.log_traceback:224 - Type: ValidationError
Class: ValidationException
Message: ValidationException:
	Message: Validation error(s): [{
    "additional_properties": {
        "debugInfo": null
    },
    "code": "UserError",
    "severity": 2,
    "message": "Y is empty",
    "message_format": "{dataName} is empty",
    "message_parameters": {
        "dataName": "Y"
    },
    "reference_code": null,
    "details_uri": null,
    "target": "training_data",
    "details": [
        {
            "additional_properties": {
                "debugInfo": null
            },
            "code": null,
            "severity": null,
            "message": "null",
            "message_format": null,
            "message_parameters": {},
            "reference_code": null,
            "details_uri": null,
            "target": null,
            "details": [],
            "inner_error": null
        }
    ],
    "inner_error": {
        "additional_properties": {},
        "code": "BadData",
        "inner_error": {
            "additional_properties": {},
            "code": "EmptyData",
            "inner_error": null
        }
    }
}]
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "inner_error": {
            "code": "ValidationError"
        },
        "message": "Validation error(s): [{\n    \"additional_properties\": {\n        \"debugInfo\": null\n    },\n    \"code\": \"UserError\",\n    \"severity\": 2,\n    \"message\": \"Y is empty\",\n    \"message_format\": \"{dataName} is empty\",\n    \"message_parameters\": {\n        \"dataName\": \"Y\"\n    },\n    \"reference_code\": null,\n    \"details_uri\": null,\n    \"target\": \"training_data\",\n    \"details\": [\n        {\n            \"additional_properties\": {\n                \"debugInfo\": null\n            },\n            \"code\": null,\n            \"severity\": null,\n            \"message\": \"null\",\n            \"message_format\": null,\n            \"message_parameters\": {},\n            \"reference_code\": null,\n            \"details_uri\": null,\n            \"target\": null,\n            \"details\": [],\n            \"inner_error\": null\n        }\n    ],\n    \"inner_error\": {\n        \"additional_properties\": {},\n        \"code\": \"BadData\",\n        \"inner_error\": {\n            \"additional_properties\": {},\n            \"code\": \"EmptyData\",\n            \"inner_error\": null\n        }\n    }\n}]"
    }
}
Traceback:
  File "_azureautomlclient.py", line 409, in fit
    test_data=test_data)
  File "_azureautomlclient.py", line 423, in _fit_remote
    validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 486, in _fit_remote_core
    training_data=training_data, validation_data=validation_data, test_data=test_data)
  File "_azureautomlclient.py", line 537, in _create_parent_run_for_remote
    test_data=test_data
  File "_azureautomlclient.py", line 616, in _create_and_validate_parent_run_dto
    self._validate_input(parent_run_dto)
  File "_azureautomlclient.py", line 694, in _validate_input
    "Validation failed. Please fix the data or settings following the validation results."

ExceptionTarget: Unspecified
2021-01-07 17:21:59.003 - INFO - 5956 - azureml.train.automl._azureautomlclient._fail_parent_run:846 - No parent run to fail
